# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ricardo Guimarães
tagline:          'Computer Scientist in KR and AI'
description:      'Computer Scientist'
url:              https://rfguimaraes.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Ricardo Guimarães'
  url:              https://rfguimaraes.github.io

paginate:         5
paginate_path:    '/posts/page:num'
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-katex

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  '/posts/index.html'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%Y-%m-%dT%H:%M:%S.%fZ'
